[build]
  functions = "lambda"
  command = "npm run prod"

[[headers]]
  for = "/static/*"
  [headers.values]
	cache-control = '''
	public,
	max-age=604800,
	must-revalidate'''
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800, must-revalidate"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"