[build]
  functions = "lambda"
  command = "npm run prod"

[[headers]]
  for = "/static/*"
  [headers.values]
    expires  = "31536000"
[[headers]]
  for = "/*.css"
  [headers.values]
    expires  = "31536000"
[[headers]]
  for = "/*.js"
  [headers.values]
    expires  = "31536000"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"